[package]
name = "rust_aoc"
version = "0.0.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
num = "0.4"
regex = { version = "1", default-features = false, features = ["std", "perf", "unicode-gencat"] }
test-case = "2.2"
