[package]
name = "year_2018"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-case = "3.0"
itertools = "0.10"
ahash = "0.8"
