[project]
name = "aoc-python"
version = "0.1.0"
description = "Advent of Code solutions implemented in Python."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = ["pytest"]
