[package]
name = "year_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
lazy_static = "1.4"
num = "0.4"
regex = "1.7"
test-case = "2.2"
phf = { version = "0.8", features = ["macros"] }
